### ISSUE TITLE
Submit new tag

### ISSUE THREAD

**Issue by MGaetan89** [2dxgujun/AndroidTagGroup#1]
Hello,

Thank you for this View!

But I can't find out to actually add a new tag (as a user) to a TagGroup. I have the input tag to enter a title, but I don't know how to "submit" the new tag. On my keyboard I only have an "Enter" key, which adds a new line. Did I forget to set something?

**Comment by 2dxgujun** [comment]
It seems the compatibility problem of the ime,
What's the ime you've been installed?

**Comment by MGaetan89** [comment]
I'm using the default Android keyboard (in Android 5.0).

**Comment by 2dxgujun** [comment]
Hi, I am using `OnEditorActionListener` to handle "Enter" key to "submit" a new tag and `OnKeyListener` to detect the "Backspace" key to delete the tag. which works fine with the third-part soft keyboard (e.g. QQ IME) or the hardware keyboard.

But it does not work with the **Google Keyboard**.

And I find the [documentation](http://developer.android.com/reference/android/view/View.OnKeyListener.html) states that the key events will only be propagated for the hardware key strokes, not software.

It is completely up to the manufacturer to honour that or to actually treat the soft and hard keyboards with equal terms.

Do you have a workaround deal with the Google Keyboard?

BTW, you can tap to blank area of the tag group to "submit" a new tag, and you can double-click the "Normal" state tag to delete it.

**Comment by MGaetan89** [comment]
Thanks for the tips, I will try to see if it works.

Maybe you could try to use [android:imeOptions](http://developer.android.com/reference/android/widget/TextView.html#attr_android:imeOptions) and listen when the user press on that key on the keyboard? (maybe `actionDone`, or let the developer choose its own).

**Comment by 2dxgujun** [comment]
Thank you, I have release the 1.1 version for some bug fixed, and a new method `submitTag()` to "submit" a new tag via code:)

**Comment by MGaetan89** [comment]
Thank you for the new release. The `submitTag()` is helpful!

I found this [SO question](http://stackoverflow.com/a/11542019/1914223) about this issue. I cloned your project and test the proposed solution, and it works.

I simply added the following in the `TagView` constructor:

``` java
setRawInputType(InputType.TYPE_CLASS_TEXT);
setImeOptions(EditorInfo.IME_ACTION_GO);
```

**Comment by 2dxgujun** [comment]
Awesome, thank you the tips.

But I don't think the _GO_ action is appropriate for the context. 

And i found a [SO question](http://stackoverflow.com/a/11377462/3790554) about detect the delete(backspace).

I will test it and keep looking for workaround :)

**Comment by MGaetan89** [comment]
Maybe you can use GO something else) by default, and let the user customise the action he wants to use (via a method like setImeOptions()).

**Comment by MGaetan89** [comment]
Do you have any news about this? Did you have time to test and find a workaround?

**Comment by broakenmedia** [comment]
Having the same issue! 'Enter' on the stock keyboard just makes a new line

**Comment by 2dxgujun** [comment]
I made some test but i didn't found how to solve it... As a workaround, you can set the `IME_ACTION_GO`.

**Comment by broakenmedia** [comment]
I think it may help if you set the edittext to singleLine 'android:singleLine="true"' the 'enter' key then becomes 'done'  and is easy to target

**Comment by 2dxgujun** [comment]
Hi, i set the edittext to singleLine, then the 'enter' key becomes 'done' and it just collapse the soft keyboard when click, no new tag added, on the Google Keyboard.

**Comment by 2dxgujun** [comment]
Hi, i set the edittext to singleLine, then the 'enter' key becomes 'done' and it just collapse the soft keyboard when click, no new tag added, on the Google Keyboard.

**Comment by 2dxgujun** [comment]
Hi, i set the edittext to singleLine, then the 'enter' key becomes 'done' and it just collapse the soft keyboard when click, no new tag added, on the Google Keyboard.
