### ISSUE TITLE
Gravity in center ?

### ISSUE THREAD

**Issue by ghysrc** [2dxgujun/AndroidTagGroup#19]
If I just add a tag, this view will align to the left of screen. But I want it in the middle of the screen. How to do that ?
OK, I solve this by adding a parent layout.
But there is another problem, if I have more than one line tags, the second line only have one tag. How to make it in the middle too ?

**Comment by 2dxgujun** [comment]
Hi, i will fix it by adding gravity support to the tags container.

**Comment by ghysrc** [comment]
Thanks.
About the second problem, I am not sure it should be in the middle or left. Because in my project, the ListActivity needs it in the left, but the DetailActivity needs it in the middle. I use buttons to achieve that...

**Comment by phamthangnd** [comment]
@ghysrc: In my app, I have more than 100 tags, and the gravity not align middle, if you solved, please help me to fix this.
But I think the solution add gravity support make this eseaier. And I watting @2dxgujun fix this.
@2dxgujun Thank for hardworking.

**Comment by leonacky** [comment]
I have fixed this problem in my forked-project
Check it:
https://github.com/leonacky/AndroidTagGroup
