### ISSUE TITLE
isAppendMode == false时，点击改变选中和非选中状态

### ISSUE THREAD

**Issue by yushilong** [2dxgujun/AndroidTagGroup#7]
在isAppendMode == false时，点击改变选中和非选中状态 该怎么做，不需要出现×

**Comment by 2dxgujun** [comment]
isAppendMode==false时，我设定这个状态为展示模式，只支持点击，不支持选中的

**Comment by yushilong** [comment]
OK，我已在你的基础上做了修改，已达到了我想要的效果，感谢！

**Comment by 2dxgujun** [comment]
o(∩_∩)o
