### ISSUE TITLE
I think 'only deletable mode' is needed

### ISSUE THREAD

**Issue by su-mong** [2dxgujun/AndroidTagGroup#82]
Thank you for providing good library. I think it is very useful and easy, so I'm satisfied with using your library.

 I think this library can be more useful if there is 'only deletable mode'. When I making my application, I need deletable tags, but I don't want 'add a new tag' function. That means, I don't want the function that users can write their own tags. So, I override your library and making my own tag library by deactivating 'appendInputTag()' function.

 I think some of this library users want this function that I made. Can you add the 'only deletable mode'? It can be useful for us.

**Comment by andrewindayang** [comment]
hi @Candykick you can take the library class. 

so gradle implement the library : 
    implementation 'me.gujun.android.taggroup:library:1.4@aar'

then take this file : https://github.com/2dxgujun/AndroidTagGroup/blob/master/library/src/main/java/me/gujun/android/taggroup/TagGroup.java

make new class into your project then extend the R.attr using your own Resources and it will automatically solved.

then 
    protected void appendInputTag() {
//        appendInputTag(null);  **//COMMENT OUT THIS LINE**
    }

THIS WILL SOLVE IT. 👯 HOPE IT HELPS!!

**Comment by su-mong** [comment]
> hi @Candykick you can take the library class.
> 
> so gradle implement the library :
> implementation 'me.gujun.android.taggroup:library:1.4@aar'
> 
> then take this file : https://github.com/2dxgujun/AndroidTagGroup/blob/master/library/src/main/java/me/gujun/android/taggroup/TagGroup.java
> 
> make new class into your project then extend the R.attr using your own Resources and it will automatically solved.
> 
> then
> protected void appendInputTag() {
> // appendInputTag(null); **//COMMENT OUT THIS LINE**
> }
> 
> THIS WILL SOLVE IT. 👯 HOPE IT HELPS!!

Oh Thank you! I did it by overriding some classes in this library, but your answer is much greater than mine.
